version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      # jenkins-ansible directory for the Dockerfile
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      # note: create the "jenkins_home" directory in the jenkins folder you created on the host machine.
      # this maps "jenkins_home" volume on host to "/var/jenkins_home" on container.
      - $PWD/jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      # centos7 directory for the Dockerfile
      context: centos7
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
  nginx:
    build:
      context: jenkins-ansible/web/
    ports:
      - "80:80"
    networks:
      - net
  fpm:
    image: php:fpm
    # seems like fpm receives the full path from nginx
    # and tries to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
      - "$PWD/data-html:/var/www/html"
    networks:
      - net
networks:
  net: